matrix:
  include:
    - language: python
      python:
        - "2.6"
        - "2.7"
        - "3.3"
        - "3.4"
        - "3.5"
        - "3.5-dev"  # 3.5 development branch
        - "3.6"
        - "3.6-dev"  # 3.6 development branch
        - "3.7-dev"  # 3.7 development branch
        - "nightly"
      # install dependencies
      before-install:
        - sudo apt-get install libzbar-dev
      install:
        - pip install -r vision/requirements.txt
      # run tests
      script:
        - py.test # or py.test for Python versions 3.5 and below
