sudo: required
language: python
python:
  - "2.7"
# install dependencies
before-install:
  - sudo apt-get install libzbar-dev
install:
  - pip install -r vision/requirements.txt
# run tests
script:
  - py.test # or py.test for Python versions 3.5 and below

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - tools
    # - platform-tools

    # The BuildTools version used by your project
    - build-tools-26.0.2

    # The SDK version used to compile your project
    - android-26

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-26

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-26
    # - sys-img-armeabi-v7a-android-17


notifications:
  slack: sdp-group13:1bnpUZZYWksC4USOF4RuL1Nw
